// Games
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';

// Game navigation
export const GET_GAME_NAVIGATION_SUCCESS = 'GET_GAME_NAVIGATION_SUCCESS';

// Dashboard
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_MATCH_SUCCESS = 'GET_MATCH_SUCCESS';
export const GET_DAY_MATCHES_SUCCESS = 'GET_DAY_MATCHES_SUCCESS';
export const PLAY_DAY_MATCHES_SUCCESS = 'PLAY_DAY_MATCH_SUCCESS';

// Login
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// Generic
export const ERROR_OCCURRED = 'ERROR_OCCURRED';
export const LOADING = 'LOADING';